;; -*- mode: eask; lexical-binding: t -*-

(package "evil-states-plus"
         "1.0.0"
         "Some extra states for evil")

(website-url "https://github.com/jgrey4296/evil-states-plus")
(keywords )

(package-file "evil-states-plus.el")
(files "*-state.el" "*-states.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "evil")
(depends-on "smerge-mode")
(depends-on "smartparens")
(depends-on "counsel")
